# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: sail up
    init: |
      composer install
      ./vendor/bin/sail build
      ./vendor/bin/sail npm install
      gp sync-done installs
    command: ./vendor/bin/sail up
  - name: npm watch
    init: gp sync-await installs
    command: ./vendor/bin/sail npm watch
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: notify
  - port: 1025
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 7700
    onOpen: ignore
  - port: 8025
    onOpen: ignore
